### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by aifya** [VitexThorn/-DCGAN-#1]
可以参考一下论文吗

**Comment by VitexThorn** [comment]
论文写得很粗糙就不发了，当时主要也是参考了这一篇学位论文：[1]王杨. 基于生成对抗网络的动漫头像生成研究[D].江西理工大学,2022.DOI:10.27176/d.cnki.gnfyc.2021.000121. 知网可以搜索到。
我的论文目录如下
![image](https://github.com/VitexThorn/Anime-Avatar-Generating_With-DCGAN/assets/54623553/df1740d7-e852-43eb-a61c-f79701752d10)
可以大致做个参考。目录中的第一、二、三组实验方案是设置生成器和判别器的训练程度不同（每经过x个batch训练一次）

**Comment by aifya** [comment]
好的，谢谢你了

**Comment by aifya** [comment]
哥有偿可以吗，真的写不下去了，可以加Q：405695569，我给你前端功能改了好多，多余的代码也都删除了。也可以看一下给我点建议
